debug: true

 
proxy:
  coll: ${COLL}
  recording: true

  enable_banner: false
  enable_wombat: true

recorder:
  dedup_policy: revisit
  dedup_index_url: 'redis://172.17.0.3:6380/0/pywb:{coll}:cdxj'
  source_coll: live
  cache: always
  rollover_size: ${ROLLOVER_SIZE}
  enable_put_custom_record: true

#autoindex: 10

#enable_auto_fetch: true

collections:
  live: $live
